### ISSUE TITLE
linux ff 41

### ISSUE THREAD

**Issue by neil-dabson** [neontribe/hipster#2]
width issue 
![2015-10-30-105311_1680x1050_scrot](https://cloud.githubusercontent.com/assets/550596/10843999/75325ff8-7ef4-11e5-9967-9641a298b0a2.png)

**Comment by neil-dabson** [comment]
bottom image scale.
![2015-10-30-105405_1680x1050_scrot](https://cloud.githubusercontent.com/assets/550596/10844011/8fc0d28c-7ef4-11e5-8862-96806fb4d197.png)

**Comment by Mottokrosh** [comment]
This should be fixed now. For Firefox apparently `img { max-width: 100% }` is not good enough, you also need to set `width: 100%`.
