### ISSUE TITLE
win 7 ie 10

### ISSUE THREAD

**Issue by neil-dabson** [neontribe/hipster#3]
oohh svg scale issues. (look at svg blog post)
![2015-10-30-105659_1680x1050_scrot](https://cloud.githubusercontent.com/assets/550596/10844076/f62b1406-7ef4-11e5-84db-f96558ae5e30.png)

**Comment by neil-dabson** [comment]
layout issues
![2015-10-30-105735_1680x1050_scrot](https://cloud.githubusercontent.com/assets/550596/10844094/0a16154c-7ef5-11e5-8ba8-101360736724.png)

**Comment by neil-dabson** [comment]
footer issue  (likely related I love this tweet bird!)
![2015-10-30-105842_1680x1050_scrot](https://cloud.githubusercontent.com/assets/550596/10844110/3187125c-7ef5-11e5-996c-503d0bda9132.png)

**Comment by Mottokrosh** [comment]
I've created a separate issue for the articles not flexing.

The SVG scaling has been fixed.
